# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
references:	# Use a package of configuration called an orb.
  default_docker_ruby_executor: &default_docker_ruby_executor	
  orbs:
    image: circleci/ruby:2.6.3-stretch-node	  # Declare a dependency on the welcome-orb
    environment:	  welcome: circleci/welcome-orb@0.4.1
      BUNDLE_JOBS: 3	# Orchestrate or schedule a set of jobs
workflows:
  version: 2	  # Name the workflow "welcome"
  build_and_test:	  
  welcome:
    # Run the welcome/run job in its own container
    jobs:	    
      - build	      
      - welcome/run
